#!/bin/sh
sudo pacman -S imagemagick networkmanager pass msmtp isync notmuch mpv \
ranger rofi vim i3lock alsa alsa-utils alsa-firmware tlp cmus arandr pulseaudio pavucontrol ladspa git base-devel &&
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ..
yay -S polybar-git zathura-pdf-mupdf i3-gaaps-rounded-git
